name: Deploy Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**' # Chá»‰ cháº¡y khi cÃ³ thay Ä‘á»•i á»Ÿ thÆ° má»¥c frontend

jobs:
  web-deploy:
    name: ğŸ‰ Deploy Frontend to InfinityFree
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4

    - name: ğŸ“‚ Sync Frontend files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./frontend/      # Láº¥y code tá»« thÆ° má»¥c nÃ y
        server-dir: ./htdocs/       # Äáº©y vÃ o thÆ° má»¥c gá»‘c cá»§a web
        exclude: |
          **/.git*
          **/.git*/**