name: Deploy Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**' # Chá»‰ cháº¡y khi cÃ³ thay Ä‘á»•i á»Ÿ thÆ° má»¥c backend

jobs:
  api-deploy:
    name: ğŸš€ Deploy Backend to InfinityFree
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4

    - name: ğŸ“‚ Sync Backend files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./backend/       # Láº¥y code tá»« thÆ° má»¥c nÃ y
        server-dir: ./htdocs/api/   # Äáº©y vÃ o thÆ° má»¥c /api
        exclude: |
          **/.git*
          **/.git*/**